# Generated by Powerlevel10k configuration wizard on 2026-03-04 at 12:55 IST.
# Based on romkatv/powerlevel10k/config/p10k-pure.zsh, checksum 7533.
# Wizard options: nerdfont-v3 + powerline, small icons, pure, original, 24h time,
# 2 lines, sparse, instant_prompt=verbose.
# Type `p10k configure` to generate another config.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases' ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob' ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # ──────────────────────────────────────────────────────────────────────────────
  # Color Palette — change ONLY here to recolor everything
  # ──────────────────────────────────────────────────────────────────────────────
  local username_color='167'       # muted red username
  local dir_color='109'            # soft desaturated cyan
  local separator_color='245'      # neutral gray for separators
  local time_color='245'           # same gray for time, "in", and "on"
  local git_branch_color='71'      # muted green git branch name
  local arrow_color='109'          # soft blue for ⇡ ⇣
  local prompt_ok_color='109'      # subtle prompt color
  local prompt_error_color='167'   # muted red on error
  local exec_time_color='179'      # soft amber for duration

  # Git status — high-contrast & bold so symbols are clearly visible
  local staged_color='72'          # muted green
  local unstaged_color='179'       # muted amber
  local untracked_color='167'      # muted red

  # ──────────────────────────────────────────────────────────────────────────────
  # Left prompt segments
  # ──────────────────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    dir
    vcs
    command_execution_time
    newline
    prompt_char
  )

  # Right prompt segments
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)

  # Basic style
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Prompt character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$prompt_ok_color
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$prompt_error_color
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

  # Username / Context
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$username_color
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO,ROOT}_CONTENT_EXPANSION="%F{$username_color}%n%f"
  typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n'

  # Directory
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$dir_color
  typeset -g POWERLEVEL9K_DIR_PREFIX="%F{$time_color}in %f"
  typeset -g POWERLEVEL9K_DIR_PREFIX_FOREGROUND=$time_color

  # ──────────────────────────────────────────────────────────────────────────────
  # Git / VCS — bold symbols + high-contrast colors
  # ──────────────────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=$git_branch_color
  typeset -g POWERLEVEL9K_VCS_PREFIX="%F{$time_color}on %f"
  typeset -g POWERLEVEL9K_VCS_PREFIX_FOREGROUND=$time_color

  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='⎇ '
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'

  # Bold + bright symbols with explicit color ids (more reliable rendering)
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON="%B%F{${staged_color}}+%f%b"
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON="%B%F{${unstaged_color}}~%f%b"
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="%B%F{${untracked_color}}?%f%b"

  # Show numbers
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED}_MAX_NUM=-1

  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=' ⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=' ⇡'
  typeset -g POWERLEVEL9K_VCS_{INCOMING,OUTGOING}_CHANGESFORMAT_FOREGROUND=$arrow_color

  typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=1

  # Spacing cleanup (no hiding)
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${P9K_CONTENT}'

  typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind)

  # Command execution time
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$exec_time_color

  # Time (right side)
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$time_color
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Other settings
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
